# Generated by Django 4.2.7 on 2024-03-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurment',
            old_name='created_at',
            new_name='date_time',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
